From almalinux:8 
ADD hello.txt  /tmp/

#the extra feature is for the ADD inst is it can be download the content from the internet apart from copyand ADD both are having same features

ADD https://github.com/nishalk09399/dockerfiles/blob/master/README.MD /tmp/